name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm test

  extra-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: highlightjs/highlight.js
      - uses: actions/checkout@v4
        with:
          path: extra/highlightjs-grammar-template
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: node tools/build.js -t cdn
      - run: git -C extra/highlightjs-grammar-template diff --exit-code dist
